import { QueryResult } from 'neo4j-driver'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { createSession } from '../internals/database'
import { PostRepository } from '../repository/PostRepository'
import styles from '../styles/Home.module.css'

type Props = {
    post_id: Number
}

const Comments: React.FC<Props> = ({post_id}) => {
  const router = useRouter()

  const [comments, setComments] = useState<QueryResult>()

  function getComments() {
    const postRepo = new PostRepository(createSession())
    
    postRepo.getComments(post_id).then(result => { 
      console.log(result)
      setComments(result) 
    }).catch(err => {
        console.log(err)
    })
  }

  useEffect(() => {

    getComments()

  }, [0])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div style={{paddingLeft: 50}}>Comments</div>
        {
          comments?.records?.map((comment, idx) => (
            <div key={idx} style={{paddingLeft: 50}}>
              <hr></hr>
              <p><a href={`${router.basePath}/profile/${comment.get('username')}`}>@{comment.get('username')}</a></p>
              <p>{comment.get('text')}</p>
              <hr></hr>
            </div>
            
          ))
        }

      </div>

     
  )
}

export default Comments
