import { QueryResult } from 'neo4j-driver'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { createSession } from '../internals/database'
import { PostRepository } from '../repository/PostRepository'
import styles from '../styles/Home.module.css'
import Comments from './comments'

const Home: NextPage = () => {
  const router = useRouter()

  const [posts, setPosts] = useState<QueryResult>()

  function getPosts() {
    const postRepo = new PostRepository(createSession())

    postRepo.getPosts().then(result => { 
      setPosts(result) 
    }).catch(err => {
      console.log(err)
    })
  }

  useEffect(() => {

    getPosts()

  }, [0])

  return (
    <div className={styles.container1}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className={styles.title} style={{paddingTop: 50}}>
            Network
        </h1>
        <hr></hr>
      </div>
      <div style={{color: 'black', background: ' rgb(255 255 255 / 70%)', paddingLeft: 50}}>

        {
          posts?.records.map((post, idx) => (
            <div key={idx}>
              <hr></hr>
              <p><a href={`${router.basePath}/profile/${post.get('username') }`}>@{post.get('username')}</a></p>
              <p>{post.get('text')}</p>
              <Comments post_id={post.get('id')}/>

              <hr></hr>
              <br></br>
            </div>
            
          ))
  
        }
      
      </div>

     
    </div>
  )
}

export default Home
